WHEEL_SIZE = 180
RAIL_LENGTH = 12786

ENCODER_REV_PULSE = 40
ENCODER_PIN_A = 23
ENCODER_PIN_B = 24
ENCODER_READ_INTERVAL = 0.2

ARDUINO_UNO_CONN = "/dev/ttyACM0"
ARDUINO_MEGA_CONN = "/dev/rfcomm0"
MOTOR_START_FORWARD = True
MOTOR_BREAK_TIME = 2
MOTOR_ARDUINO_ID = 4000