WHEEL_SIZE = 183
RAIL_LENGTH = 13192
ENCODER_REV_PULSE = 80

ARDUINO_UNO_CONN = "/dev/ttyACM1"
ARDUINO_UNO_TRIGGER_ENCODER_CONN = "/dev/ttyACM0"
ARDUINO_MEGA_CONN = "/dev/rfcomm0"

MOTOR_START_FORWARD = True
MOTOR_BREAK_TIME = 2

TRIGGER_SONY_DOWN = 87
TRIGGER_SONY_UP = 90