WHEEL_SIZE = 183
RAIL_LENGTH = 13014
ENCODER_REV_PULSE = 160

ARDUINO_UNO_CONN = "/dev/ttyACM0"
ARDUINO_UNO_TRIGGER_ENCODER_CONN = "/dev/ttyACM1"
ARDUINO_MEGA_CONN = "/dev/rfcomm0"
ARDUINO_MEGA_CONN_MAC = "/dev/tty.HC-06-SPPDev"
MOTOR_START_FORWARD = True
MOTOR_BREAK_TIME = 2
MOTOR_ARDUINO_ID = 4000