WHEEL_SIZE = 183
RAIL_LENGTH = 13192
ENCODER_REV_PULSE = 80

ARDUINO_UNO_CONN = "/dev/ttyACM0"
ARDUINO_UNO_TRIGGER_ENCODER_CONN = "/dev/ttyACM0"
ARDUINO_MEGA_CONN = "192.168.4.1" # "10.0.0.11"

TRIGGER_SONY_DOWN = 88
TRIGGER_SONY_UP = 94

SPEED_KP = 0.08
SPEED_KI = 0
SPEED_KD = 0.05

MOTOR_START_FORWARD = True
MOTOR_BREAK_TIME = 2
MOTOR_STEP_TIME = 20
MOTOR_MAXIMUM_STATE = 130
MOTOR_MAXIMUM_SPEED = 180
MOTOR_CLOCKWISE = 1
MOTOR_COUNTERCLOCKWISE = -1

WIFI_SSID = "______________"
WIFI_PWD = "kerze123!"

ESP_SSID = "Old_Weller"
ESP_PWD = "wellalright!"